release:
  github:
    owner: duck8823
    name: duci
builds:
  - binary: duci
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md
    - LICENSE
  replacements:
    darwin: mac
    amd64: 64bit
    386: 32bit
