sudo: required
services:
  - docker

language: go
go:
  - tip
  - "1.10"

cache:
  directories:
    - $GOPATH/pkg/mod/cache

install: true
before_script:
  # ssh settings
  - openssl aes-256-cbc -K $encrypted_a66fdba2821d_key -iv $encrypted_a66fdba2821d_iv -in .travis/travis_key.enc -out ~/.ssh/id_rsa -d
  - touch ~/.ssh/known_hosts
  # for coverage report
  - go get github.com/mattn/goveralls
  # using vgo for resolve dependencies
  - go get golang.org/x/vgo
script:
  - vgo test -coverprofile cover.out $(vgo list ./... | grep -v mock_)
after_success:
  - if [ "$TRAVIS_GO_VERSION" = "1.10" ]; then goveralls -service=travis-ci -coverprofile=cover.out -ignore=main.go; fi
before_deploy:
  - go get -u github.com/golang/dep/cmd/dep
  - dep init
  - go get -u github.com/buchanae/github-release-notes
  - github-release-notes -org duck8823 -repo duci -since-latest-release > release-notes.txt
  - go get -u github.com/goreleaser/goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash --release-notes=release-notes.txt
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION = "1.10"