sudo: required
services:
  - docker

language: go
go:
  - tip
  - "1.11"

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod/cache

install: true
before_script:
  # ssh settings
  - openssl aes-256-cbc -K $encrypted_a66fdba2821d_key -iv $encrypted_a66fdba2821d_iv -in .travis/travis_key.enc -out ~/.ssh/id_rsa -d
  - touch ~/.ssh/known_hosts
  # download dependencies
  - go mod download
script:
  - go test -coverprofile cover.out $(go list ./... | grep -v mock_)
after_success:
  # for coverage report
  - GO111MODULE=off go get -u github.com/mattn/goveralls
  - if [ "$TRAVIS_GO_VERSION" = "1.11" ]; then goveralls -service=travis-ci -coverprofile=cover.out -ignore=main.go; fi
  # for reviewdog
  - GO111MODULE=off go get -u github.com/haya14busa/reviewdog/cmd/reviewdog
  - GO111MODULE=off go get github.com/golang/lint/golint
  - GO111MODULE=off go get github.com/kisielk/errcheck
  - GO111MODULE=off go get honnef.co/go/tools/cmd/gosimple
  - GO111MODULE=off go get honnef.co/go/tools/cmd/staticcheck
  - GO111MODULE=off go get honnef.co/go/tools/cmd/unused
  - GO111MODULE=off go get github.com/client9/misspell/cmd/misspell
  - GO111MODULE=off go get mvdan.cc/unparam
  - GO111MODULE=off go get github.com/mgechev/revive
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin
  - if [ "$TRAVIS_GO_VERSION" = "1.11" ]; then reviewdog -reporter=github-pr-check; fi
before_deploy:
  # copy dependencies to vendor
  - go mod vendor
  - GO111MODULE=off go get -u github.com/buchanae/github-release-notes
  - GO111MODULE=off go get -u github.com/goreleaser/goreleaser
  - github-release-notes -org duck8823 -repo duci -since-latest-release > release-notes.txt
deploy:
  - provider: script
    skip_cleanup: true
    script: goreleaser --release-notes=release-notes.txt
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION = "1.11"