sudo: required
services:
  - docker

language: go
go:
  - tip

install: true
before_script:
  # ssh settings
  - openssl aes-256-cbc -K $encrypted_a66fdba2821d_key -iv $encrypted_a66fdba2821d_iv -in .travis/travis_key.enc -out ~/.ssh/id_rsa -d
  - touch ~/.ssh/known_hosts
  # for coverage report
  - go get github.com/mattn/goveralls
  # using vgo for resolve dependencies
  - go get golang.org/x/vgo
script:
  - vgo test -v -coverprofile=cover.out ./...
  - goveralls -service=travis-ci -coverprofile=cover.out -ignore=main.go,mocks/*/*
after_script:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash