version: "2"
services:
  duci:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - $HOME/.ssh:/root/.ssh:ro
    environment:
      - DOCKER_HOST=tcp://docker.for.mac.host.internal:2375
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
#  ngrok:
#    image: wernight/ngrok
#    command: "ngrok http duci:8080"
#    ports:
#      - 4040:4040
  socat:
    image: bobrik/socat
    command: TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
