version: "2"
services:
  webhook-proxy:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DOCKER_HOST=tcp://docker.for.win.host.internal:2375
  ngrok:
    image: wernight/ngrok
    command: "ngrok http webhook-proxy:8080"
    ports:
      - 4040:4040
#  socat:
#    image: bobrik/socat
#    command: TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
#    ports:
#      - 2375:2375
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
