version: "2"
services:
  webhook-proxy:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DOCKER_HOST=tcp://docker.for.mac.host.internal:1234
      - DANGER_GITHUB_API_TOKEN=${DANGER_GITHUB_API_TOKEN}
  ngrok:
    image: wernight/ngrok
    command: "ngrok http webhook-proxy:8080"
    ports:
      - 4040:4040
  socat:
    image: bobrik/socat
    command: TCP-LISTEN:1234,fork UNIX-CONNECT:/var/run/docker.sock
    ports:
      - 1234:1234
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
